sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ganderohit/frontend-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true ganderohit/frontend-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-292336901939'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
