sudo: required
language: generic
services:
  - docker

before_install:
  - docker buiild -t ganderohit/frontend-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/frontend-docker npm run test -- --coverage
